Update DOM.js
gre/kenburns pull request #8
Opened 2016-12-21 17:04 UTC by strarsis

This improves aliasing/reduces jagged edges when images are scaled.
see http://stackoverflow.com/questions/6492027/css-transform-jagged-edges-in-chrome

2016-12-22 11:38 UTC, gre commented
thanks for this !

2016-12-22 11:38 UTC, gre requested changes

2016-12-22 11:38 UTC, gre commented on src/DOM.js
> +      source.style.boxShadow = '0 0 1px rgba(255,255,255,0)'; // "
minor code style note: can you switch ' to "  and remove the `// "` ? a link to the stackoverflow in the comment can be good to track this for later too :)

2016-12-22 11:39 UTC, gre commented on src/DOM.js
> +      source.style.boxShadow = '0 0 1px rgba(255,255,255,0)'; // "
Also, I don't think `.style['-webkit-backface-visibility']` works. I think it should be `.style.WebkitBackfaceVisibility`

2016-12-22 11:40 UTC, gre commented on src/DOM.js
> +      source.style.boxShadow = '0 0 1px rgba(255,255,255,0)'; // "
but it does not seem to exist anymore, not in chrome at least, is if for another browser?

2016-12-22 11:41 UTC, gre commented on src/DOM.js
> +      source.style.boxShadow = '0 0 1px rgba(255,255,255,0)'; // "
yeah, it exists in Safari

<img width="437" alt="screen shot 2016-12-22 at 12 41 30" src="https://cloud.githubusercontent.com/assets/211411/21424576/01588004-c844-11e6-8a58-0e85f277ce29.png">

2016-12-22 17:16 UTC, strarsis commented
Yes, I removed the // " and formatted those lines into one block with one comment and link to the SO thread, quotes were changed to double-quotes.

The css property access is a bit confusing, it appears that the property name has to start with an uppercase letter in order to prefix with '-' (http://stackoverflow.com/questions/9438949/access-the-webkit-vendor-prefix-in-javascript).

2016-12-23 10:12 UTC, gre commented
interesting, I didn't know about this uppercase thing.

2016-12-23 10:13 UTC, merged